apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-deployment
  namespace: default
  annotations:
    deployment.kubernetes.io/revision: '3'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"model-deployment","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"model"}},"template":{"metadata":{"labels":{"app":"model"}},"spec":{"containers":[{"image":"mlops01-m3-mlops01-m4-1","name":"mlops01-m4","ports":[{"containerPort":5000}]}]}}}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: model
  template:
    metadata:
      labels:
        app: model
      annotations:
        kubectl.kubernetes.io/restartedAt: '2025-01-26T20:09:02Z'
    spec:
      containers:
      - name: mlops01-m4
        image: mlops01-m3-mlops01-m4-1
        ports:
        - containerPort: 5000
          protocol: TCP
        imagePullPolicy: Always
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
